# Generated by Django 6.0.4 on 2026-05-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('national_position', models.CharField(blank=True, max_length=50, null=True)),
                ('club', models.CharField(max_length=100)),
                ('club_position', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.IntegerField()),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField()),
                ('skill_moves', models.IntegerField(default=0)),
                ('ball_control', models.FloatField(default=0)),
                ('dribbling', models.FloatField(default=0)),
                ('speed', models.FloatField(default=0)),
                ('strength', models.FloatField(default=0)),
                ('player_level', models.CharField(choices=[('Elite', 'Elite'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], default='Bronze', max_length=20)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
